name: Export workflow from a private repository

on:
  workflow_run:
    workflows:
      # The name of the workflow(s) that triggers the export
      - "My workflow"
    types: [completed]

jobs:
  otel-export-private:
    runs-on: ubuntu-latest
    # Permissions can be set on a per-job basis or at the top level
    permissions:
      contents: read # To access the private repository
      actions: read # To read workflow runs
      pull-requests: read # To read PR labels
    steps:
      - uses: actions/checkout@v4
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v1
        with:
          otlpEndpoint: "CHANGE_ME"
          otlpHeaders: "CHANGE_ME"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
